site_name: trivium
site_url: http://www.trivium.io

site_description: trivium project documentation
repo_url: https://github.com/trivium-io/trivium/

pages:
- Home: index.md
- Fact:
  - Overview: fact.md
  - builtin:
    - File: fact/file.md
    - LogEntry: fact/logentry.md
- Task:
  - Overview: task.md
  - builtin:
    - ConsoleLogger: task/consolelogger.md
- Binding:
  - Overview: binding.md
  - builtin:
    - WebObjectHandler: binding/webobjecthandler.md
    - WebUI: binding/webui.md
- Samples:
  - TimerSample: samples/timersample.md
