site_name: trivium
site_url: http://www.trivium.io
site_favicon: favicon.ico
site_description: trivium project documentation
repo_url: https://github.com/trivium-io/trivium/

pages:
- Home: index.md
- Fact:
  - Overview: fact.md
  - builtin facts:
    - File: fact/file.md
    - LogEntry: fact/logentry.md
    - empty fact template: fact/template.md
- Task:
  - Overview: task.md
  - builtin tasks:
    - ConsoleLogger: task/consolelogger.md
    - empty task template: task/template.md
- Binding:
  - Overview: binding.md
  - builtin bindings:
    - WebObjectHandler: binding/webobjecthandler.md
    - WebUI: binding/webui.md
- how-tos:
  - custom fact serializer: customfactserializer.md
- internal stuff:
  - TriviumObject: triviumobject.md
  - Element: element.md
  - Serializer: serlializer.md
- Samples:
  - TimerSample: samples/timersample.md
